<Project Sdk="MSBuild.Sdk.Extras">
  <PropertyGroup>
    <TargetFrameworks>net9.0;</TargetFrameworks>
    <NoWarn>CS3001</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('monoandroid'))">
    <DefineConstants>$(DefineConstants);ANDROID</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(TargetFramework.StartsWith('xamarin.ios'))">
    <DefineConstants>$(DefineConstants);IOS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Condition="$(TargetFramework) == 'net462'" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Sbom.Targets" PrivateAssets="all" Condition="$(Configuration)=='Release'" />
  </ItemGroup>
</Project>
